#!/bin/bash

#sudo apt-get install xclip
#sudo easy_install -ZU autopep8 
cd ~
echo "Ljc 正在为您安装配套程序" > Ljc
sudo apt-get install vim-gtk ctags cscope astyle git subversion

# backup
rm -rf ~/vim_ljc ~/.vim_old
mv -f ~/.vimrc ~/.vimrc_old
mv -f ~/.vim ~/.vim_old

# new files
echo "请耐心等待" >> Ljc
svn checkout https://github.com/Will-Grindelwald/Linux-Configuration/trunk/Vim ~/vim_ljc
mv -f ~/vim_ljc/.vimrc ~/.vimrc
mv -f ~/vim_ljc ~/.vim

# Plugin
echo "正在安装插件, 花费时间取决于你的网速" > Ljc
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
echo "安装完毕将自动退出" >> Ljc
echo "请耐心等待" >> Ljc
vim Ljc +"PluginInstall" +"qa"
rm -rf ~/.vim/.svn ~/.vim/README.md ~/.vim/setup Ljc
vim +"helptags ~/.vim/doc" +"qa"
echo "安装完成"

